### ISSUE TITLE
db 연결 문제

### ISSUE THREAD

**Issue by parkj12b** [jiphyeonjeon-42/backend-nest#73]
backend-1   | Not enough non-option arguments: got 0, need at least 1
에러 해결 방법을 모르겠습니다...

**Comment by scarf005** [comment]
마이그레이션이랑 관련이 있는 오류인 것 같네요 https://stackoverflow.com/questions/72682474/typeorm-migrationgenerate-failure-not-enough-non-option-arguments-got-0-need

혹시 전체 오류 메시지와 어떤 명령어 실행했는지도 알려주실수 있을까요?

**Comment by parkj12b** [comment]
root 에서 pnpm dev 실행했습니다. container 들어가서 실행해도 바뀌지 않네요 
![image](https://github.com/user-attachments/assets/e91b2a70-1f4f-4dea-b391-53115fcd99f3)

**Comment by jimin52** [comment]
main 으로 rollback 해서 성공
